import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Read the CSV file generated by your MPI program
# We set index_col=0 because we saved the row labels
try:
    df = pd.read_csv("heatmap_reduce_scatter.csv", index_col=0)
except FileNotFoundError:
    print("Error: heatmap_data_algo1.csv not found.")
    print("Please compile and run the MPI C code first.")
    exit()

# Create the heatmap
plt.figure(figsize=(10, 8))
# 'annot=True' writes the data values in each cell (remove for large p)
# 'fmt='g'' formats numbers nicely
# 'cmap="viridis"' is a nice color map (you can also use "hot", "inferno", etc.)
sns.heatmap(
    df, 
    annot=True, 
    fmt='g', 
    cmap="viridis", 
    linewidths=.5,
    cbar_kws={'label': 'Communication Volume (Bytes)'} # Color bar label
)

# Add titles and labels
plt.title("Communication Heatmap: Algorithm 1 (Reduce-scatter)")
plt.xlabel("Destination Rank (Receives)")
plt.ylabel("Source Rank (Sends)")
plt.tight_layout()

# Save the plot
plt.savefig("heatmap_algo1_reduce_scatter.png")
print("Heatmap saved to heatmap_algo1.png")
